### ISSUE TITLE
Locked to livewire dev-master

### ISSUE THREAD

**Issue by Pen-y-Fan** [blockpc/select2-wire#1]
I'm unable to require the package as I already have livewire v2.6 installed, but this package is locked to `"livewire/livewire": "dev-master"`. The composer.json probably needs to be changed to `"livewire/livewire": "^2"`

**Comment by blockpc** [comment]
Thanks, I try to fix livewire to `"livewire/livewire": "^2.6"`
its a new tag 1.1.1
Thank you, I hope I have fixed the problem well.
In the examples repository it worked
